slam_toolbox:
  ros__parameters:

    use_sim_time: false
    mode: mapping

    map_frame: map
    odom_frame: odom
    base_frame: base_link

    scan_topic: /scan

    # QoS สำคัญ
    qos_overrides:
      /scan:
        reliability: best_effort
        durability: volatile
        history: keep_last
        depth: 5

    resolution: 0.05
    max_laser_range: 12.0

    minimum_time_interval: 0.1
    transform_timeout: 0.2

    use_imu: true
    imu_topic: /imu

    publish_tf: true
